name: Testando action com comandos
on: 
  # pull_request: 
  #   branches:
  #     - 'main'
  push:
    branches: 
      - 'main'
jobs:
  Hello-Job-1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Execucao do meu primeiro Job"
      - run: echo "Varios comandos"
